name: 'CI check'
on: [push, pull_request]
jobs:
    shellcheck:
        name: 'Shellcheck'
        runs-on: ubuntu-latest
        steps:
            - name: 'Check out the code'
              uses: actions/checkout@v1

            - name: 'Run Shellcheck'
              uses: azohra/shell-linter@v0.6.0
    docker_checker:
        name: 'Docker Sanity checker'
        runs-on: ubuntu-latest
        steps:
            - name: 'Check out the code'
              uses: actions/checkout@v1

            - name: 'Build docker image'
              uses: docker/build-push-action@v2
              with:
                tags: test-image:latest
                push: false

            - name: 'Run command inside the docker container'
              uses: addnab/docker-run-action@v3
              with:
                image: test-image:latest
                run: echo "hello world"

