name: 'CI check'
on: [push, pull_request]
jobs:
    shellcheck:
        name: 'Shellcheck'
        runs-on: ubuntu-latest
        steps:
            - name: 'Check out the code'
              uses: actions/checkout@v1

            - name: 'Run Shellcheck'
              uses: azohra/shell-linter@v0.6.0
    docker_checker:
        name: 'Docker Sanity checker'
        runs-on: ubuntu-latest
        steps:
            - name: 'Check out the code'
              uses: actions/checkout@v1

            - name: 'Build docker image'
              uses: docker/build-push-action@v2
              with:
                tags: repoman-repo-qa:latest
                push: false

            - name: 'Run command inside the docker container'
              env:
                  INPUT_GENTOO_REPO: /tmp 
                  INPUT_PORTAGE_VERSION: latest
                  INPUT_PROFILE: latest
                  INPUT_PATH: /tmp
                  INPUT_REPOMAN_ARGS: -p
              uses: addnab/docker-run-action@v3
              with:
                image: repoman-repo-qa:latest
                options: --env INPUT_REPOMAN_ARGS=-p --env INPUT_GENTOO_REPO=/usr/portage --env INPUT_PORTAGE_VERSION=latest --env INPUT_PROFILE=latest --env INPUT_PATH=/tmp
                  #run: printenv
                run: /entrypoint.sh
